version: '3.8'
services:
  web:
    build: .
    image: xlibris/web:latest
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
    ports:
      - "5000:5000"
    networks:
      - captain-network

networks:
  captain-network:
    external: true
