import bcrypt from 'bcrypt';
import dotenv from 'dotenv';
import postgres from 'postgres';

dotenv.config();

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) {
  throw new Error('DATABASE_URL is required in .tmp/ui-test-runner/.env');
}

const sql = postgres(databaseUrl, { max: 1 });

const password = process.env.VOXLIBRIS_OWNER_PASSWORD ?? 'VoxLibrisUiTest123!';
const passwordHash = await bcrypt.hash(password, 10);

const users = [
  { id: 'vl-ui-owner', username: 'vl_ui_owner', email: process.env.VOXLIBRIS_OWNER_EMAIL ?? 'vl-ui-owner@example.test', displayName: 'VL UI Owner' },
  { id: 'vl-ui-member', username: 'vl_ui_member', email: process.env.VOXLIBRIS_MEMBER_EMAIL ?? 'vl-ui-member@example.test', displayName: 'VL UI Member' },
  { id: 'vl-ui-other-member', username: 'vl_ui_other_member', email: process.env.VOXLIBRIS_OTHER_MEMBER_EMAIL ?? 'vl-ui-other-member@example.test', displayName: 'VL UI Other Member' },
  { id: 'vl-ui-non-member', username: 'vl_ui_non_member', email: process.env.VOXLIBRIS_NON_MEMBER_EMAIL ?? 'vl-ui-non-member@example.test', displayName: 'VL UI Non Member' },
];

const standardClubId = process.env.VOXLIBRIS_STANDARD_CLUB_ID ?? 'vl-ui-standard-club';
const readerClubId = process.env.VOXLIBRIS_READER_CLUB_ID ?? 'vl-ui-reader-club';
const otherClubId = process.env.VOXLIBRIS_OTHER_CLUB_ID ?? 'vl-ui-other-club';

await sql.begin(async (tx) => {
  for (const user of users) {
    await tx`
      INSERT INTO users (id, username, email, password, role, status, email_confirmed)
      VALUES (${user.id}, ${user.username}, ${user.email}, ${passwordHash}, 'admin', 'active', true)
      ON CONFLICT (id) DO UPDATE SET
        username = EXCLUDED.username,
        email = EXCLUDED.email,
        password = EXCLUDED.password,
        role = EXCLUDED.role,
        status = EXCLUDED.status,
        email_confirmed = EXCLUDED.email_confirmed
    `;
    await tx`
      INSERT INTO user_profiles (user_id, display_name, is_reader, reader_rating)
      VALUES (${user.id}, ${user.displayName}, true, 450)
      ON CONFLICT (user_id) DO UPDATE SET
        display_name = EXCLUDED.display_name,
        is_reader = EXCLUDED.is_reader,
        reader_rating = EXCLUDED.reader_rating
    `;
  }

  await tx`
    INSERT INTO clubs (id, title, description, owner_id, type, status, max_members, is_private, is_active, settings)
    VALUES (${standardClubId}, 'VL UI Standard Club', 'Autogenerated standard moderation test club', 'vl-ui-owner', 'standard', 'active', 100, false, true, '{}')
    ON CONFLICT (id) DO UPDATE SET
      title = EXCLUDED.title,
      description = EXCLUDED.description,
      owner_id = EXCLUDED.owner_id,
      type = EXCLUDED.type,
      status = EXCLUDED.status,
      max_members = EXCLUDED.max_members,
      is_private = EXCLUDED.is_private,
      is_active = EXCLUDED.is_active,
      settings = EXCLUDED.settings
  `;

  await tx`
    INSERT INTO clubs (id, title, description, owner_id, type, status, max_members, is_private, is_active, settings)
    VALUES (${readerClubId}, 'VL UI Reader Club', 'Autogenerated reader-led moderation test club', 'vl-ui-owner', 'reader-led', 'active', 100, false, true, '{"readerJoinRequestsEnabled":true}')
    ON CONFLICT (id) DO UPDATE SET
      title = EXCLUDED.title,
      description = EXCLUDED.description,
      owner_id = EXCLUDED.owner_id,
      type = EXCLUDED.type,
      status = EXCLUDED.status,
      max_members = EXCLUDED.max_members,
      is_private = EXCLUDED.is_private,
      is_active = EXCLUDED.is_active,
      settings = EXCLUDED.settings
  `;

  await tx`
    INSERT INTO clubs (id, title, description, owner_id, type, status, max_members, is_private, is_active, settings)
    VALUES (${otherClubId}, 'VL UI Other Club', 'Autogenerated control club', 'vl-ui-owner', 'standard', 'active', 100, false, true, '{}')
    ON CONFLICT (id) DO UPDATE SET
      title = EXCLUDED.title,
      description = EXCLUDED.description,
      owner_id = EXCLUDED.owner_id,
      type = EXCLUDED.type,
      status = EXCLUDED.status,
      max_members = EXCLUDED.max_members,
      is_private = EXCLUDED.is_private,
      is_active = EXCLUDED.is_active,
      settings = EXCLUDED.settings
  `;

  await tx`DELETE FROM club_members WHERE club_id IN (${standardClubId}, ${readerClubId}, ${otherClubId})`;

  for (const clubId of [standardClubId, readerClubId, otherClubId]) {
    await tx`
      INSERT INTO club_members (club_id, user_id, role, is_active, muted_until, deactivated_until, restriction_reason, restricted_by, restricted_at)
      VALUES (${clubId}, 'vl-ui-owner', 'owner', true, null, null, null, null, null)
    `;
    await tx`
      INSERT INTO club_members (club_id, user_id, role, is_active, muted_until, deactivated_until, restriction_reason, restricted_by, restricted_at)
      VALUES (${clubId}, 'vl-ui-member', 'member', true, null, null, null, null, null)
    `;
  }

  for (const clubId of [standardClubId, readerClubId]) {
    await tx`
      INSERT INTO club_members (club_id, user_id, role, is_active, muted_until, deactivated_until, restriction_reason, restricted_by, restricted_at)
      VALUES (${clubId}, 'vl-ui-other-member', 'member', true, null, null, null, null, null)
    `;
  }
});

await sql.end();
console.warn('VoxLibris UI test data seeded');
